export const FETCH_GITHUB_REPO = 'FETCH_GITHUB_REPO';
export const FETCH_GITHUB_REPO_SUCCESS = 'FETCH_GITHUB_REPO_SUCCESS';
export const FETCH_GITHUB_REPO_FAILURE = 'FETCH_GITHUB_REPO_FAILURE';

export const UPDATE_PAGE = 'UPDATE_PAGE';

export const GO_TO_NEXT_SET = 'GO_TO_NEXT_SET';
export const GO_TO_PREVIOUS_SET = 'GO_TO_PREVIOUS_SET';

export const NEXT_SET_CHANGE_FAILURE = 'NEXT_SET_CHANGE_FAILURE';
export const NEXT_SET_CHANGE_SUCCESS = 'NEXT_SET_CHANGE_SUCCESS';

export const PREVIOUS_SET_CHANGE_FAILURE = 'PREVIOUS_SET_CHANGE_FAILURE';
export const PREVIOUS_SET_CHANGE_SUCCESS = 'PREVIOUS_SET_CHANGE_SUCCESS';